# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  cheesygine_core_config = debug
  cheesygine_runtime_config = debug
  glfw_config = debug
  glew_config = debug

else ifeq ($(config),release)
  cheesygine_core_config = release
  cheesygine_runtime_config = release
  glfw_config = release
  glew_config = release

else ifeq ($(config),dist)
  cheesygine_core_config = dist
  cheesygine_runtime_config = dist
  glfw_config = dist
  glew_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := cheesygine_core cheesygine_runtime glfw glew

.PHONY: all clean help $(PROJECTS) core

all: $(PROJECTS)

core: cheesygine_core

cheesygine_core: glfw glew
ifneq (,$(cheesygine_core_config))
	@echo "==== Building cheesygine_core ($(cheesygine_core_config)) ===="
	@${MAKE} --no-print-directory -C cheesygine_core -f Makefile config=$(cheesygine_core_config)
endif

cheesygine_runtime: cheesygine_core glfw glew
ifneq (,$(cheesygine_runtime_config))
	@echo "==== Building cheesygine_runtime ($(cheesygine_runtime_config)) ===="
	@${MAKE} --no-print-directory -C cheesygine_runtime -f Makefile config=$(cheesygine_runtime_config)
endif

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C vendor -f glfw.make config=$(glfw_config)
endif

glew:
ifneq (,$(glew_config))
	@echo "==== Building glew ($(glew_config)) ===="
	@${MAKE} --no-print-directory -C vendor -f glew.make config=$(glew_config)
endif

clean:
	@${MAKE} --no-print-directory -C cheesygine_core -f Makefile clean
	@${MAKE} --no-print-directory -C cheesygine_runtime -f Makefile clean
	@${MAKE} --no-print-directory -C vendor -f glfw.make clean
	@${MAKE} --no-print-directory -C vendor -f glew.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cheesygine_core"
	@echo "   cheesygine_runtime"
	@echo "   glfw"
	@echo "   glew"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"